[[constraint]]
  branch = "master"
  name = "github.com/kubernetes-csi/drivers"

[[constraint]]
  branch = "v0.3.0"
  name = "github.com/kubernetes-csi/csi-test"

[[constraint]]
  name = "github.com/gluster/glusterd2"
  branch = "master"

[[constraint]]
  name = "github.com/container-storage-interface/spec"
  version = "~0.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[override]]
  revision = "5db89f0ca68677abc5eefce8f2a0a772c98ba52d"
  name = "github.com/docker/distribution"

[[override]]
  branch = "release-branch.go1.10"
  name = "golang.org/x/net"

[[override]]
  name = "github.com/pborman/uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.10.0"

[[override]]
  version = "kubernetes-1.12.0"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "v1.12.0"

[[override]]
  version = "kubernetes-1.12.0"
  name = "k8s.io/api"

[[override]]
  name = "github.com/golang/protobuf"
  version = "v1.1.0"
