[[constraint]]
  version = "1.0.0"
  name = "github.com/kubernetes-csi/drivers"

[[constraint]]
  version = "1.0.0-2"
  name = "github.com/kubernetes-csi/csi-test"

[[constraint]]
  name = "github.com/gluster/glusterd2"
  branch = "master"

[[constraint]]
  name = "github.com/container-storage-interface/spec"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[override]]
  name = "github.com/Sirupsen/logrus"
  source = "github.com/sirupsen/logrus"

[[override]]
  revision = "5db89f0ca68677abc5eefce8f2a0a772c98ba52d"
  name = "github.com/docker/distribution"

[[override]]
  branch = "release-branch.go1.10"
  name = "golang.org/x/net"

[[override]]
  name = "github.com/pborman/uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.10.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "v1.13.1"

[[override]]
  version = "kubernetes-1.13.1"
  name = "k8s.io/api"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.1"

[[override]]
  version = "kubernetes-1.13.1"
  name = "k8s.io/apiserver"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.1"

[[override]]
  name = "github.com/golang/protobuf"
  version = "v1.1.0"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true
